app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('list/', views.ListView.as_view(), name='list'),
    path('detail/<int:id>/', views.DetailView.as_view(), name='detail'),
    path('contact/', views.ContactFormView.as_view(), name='contact_form'),
    path('contact/result/', views.ContactResultView.as_view(), name='contact_result'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')), 
    path('summernote/', include('django_summernote.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# カテゴリマスタ
class m_category(models.Model):
    name = models.CharField('カテゴリ', max_length=50)

    def __str__(self):
        return self.name

# タグマスタ
class m_tag(models.Model):
    name = models.CharField('タグ', max_length=50)

    def __str__(self):
        return self.name
    
# テーブル
class t_table(models.Model):
    category = models.ForeignKey(
                m_category, verbose_name='カテゴリ',
                on_delete=models.PROTECT
            )
    tag = models.ManyToManyField(m_tag, verbose_name='タグ', null=True, blank=True)
    title = models.CharField(verbose_name='タイトル', max_length=200)
    content = models.TextField(verbose_name='内容')
    image = models.ImageField(verbose_name = '画像',upload_to = 'images/')
    newadddate = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updatedate = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    deletedate = models.DateTimeField(verbose_name='削除日時', null=True, blank=True)
    views = models.PositiveIntegerField(verbose_name='閲覧数', default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-newadddate',) 

app/forms.py
from django import forms
from .models import m_category, m_tag
from django.conf import settings
from django.http import HttpResponse
from django.core.mail import BadHeaderError, send_mail

#　検索フォーム
class SearchForm(forms.Form):    
    keyword = forms.CharField(label='キーワード', max_length=100, required=False,
                                widget=forms.TextInput(attrs={"class":"form-control"}))
    category = forms.ModelChoiceField(label='カテゴリ', empty_label='未選択', queryset=m_category.objects.all(), required=False,
                                        widget=forms.Select(attrs={"class":"form-select"}))
    tag = forms.ModelChoiceField(label='タグ', empty_label='未選択', 
                                queryset=m_tag.objects.all(), 
                                required=False,
                                widget=forms.Select(attrs={"class":"form-select"}))

    ORDER_CHOICES = (
        ('newadddate', '新着順'),
        ('views', '人気順'),
    )

    order = forms.fields.ChoiceField(
        choices=ORDER_CHOICES,
        initial = 'newadddate',
        required=False,
        label='並び替え',
        widget=forms.Select(attrs={"class":"form-select"})
    )

#　お問い合わせフォーム
class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

app/views.py
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, FormView
from .models import t_table
from .forms import ContactForm, SearchForm
from django.core.paginator import Paginator
from django.db.models import Q

# 一覧画面
class ListView(TemplateView):
    template_name = 'list.html'

    def get_context_data(self, **kwargs):
        # パラメータの作成
        deletedate = Q(deletedate__isnull=True)
        newadddate = Q(newadddate__lte=timezone.now())
        category   = Q()
        tag        = Q()
        keyword    = Q()
        order      = 'newadddate'
        page       = 1
        # GETパラメータ取得
        if "category" in self.request.GET:
            param_category=self.request.GET.get('category')
            if param_category != "" :
                category = Q(category=param_category)
        if "tag" in self.request.GET:
            param_tag=self.request.GET.get('tag')
            if param_tag != "" :
                tag = Q(tag=param_tag)
        if "keyword" in self.request.GET:
            param_keyword=self.request.GET.get('keyword')
            if param_keyword != "" :
                keyword = Q(title__icontains=param_keyword) | Q(content__icontains=param_keyword)
        if "order" in self.request.GET:
            order=self.request.GET.get('order')
        #　データ取得
        table = t_table.objects.filter(deletedate & newadddate & category & tag & keyword).order_by('-' + order)

        # ページネーション
        if "page" in self.request.GET:
            page = self.request.GET.get('page') 
        paginator = Paginator(table, 20)       # 1ページに表示する件数
        list = paginator.get_page(page)        # 指定のページのデータ取得

        context = super().get_context_data(**kwargs)
        context['list'] = list
        context['searchform'] = SearchForm(self.request.GET)
        return context

# 詳細画面
class DetailView(TemplateView):
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        # パラメータ作成
        deletedate = Q(deletedate__isnull=True)
        newadddate = Q(newadddate__lte=timezone.now())
        # 対象データ取得
        detail = get_object_or_404(t_table.objects.filter(deletedate & newadddate), id=self.kwargs['id'])

        # 閲覧数の加算
        detail.views += 1
        detail.save()
        
        context = super().get_context_data(**kwargs)
        context['detail'] = detail
        return context

# お問合せ画面
class ContactFormView(FormView):
    template_name = 'contact_form.html'
    form_class = ContactForm
    success_url = reverse_lazy('app:contact_result')
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

# お問合せ完了画面
class ContactResultView(TemplateView):
    template_name = 'contact_result.html'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!doctype html>
<html>

<head>
    <!-- BASE -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    {% endblock %}
    <title>Sample</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}" sizes="any"><!-- 32×32 -->
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}"><!-- 180×180 -->
    <link rel="manifest" href="{% static 'json/manifest.webmanifest' %}">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <!-- CSS -->
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <!-- JS -->
    {% bootstrap_javascript %}
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/style.js' %}"></script>
</head>

<body>
    <header class="header sticky-top">
        <!-- ナビゲーションメニュー -->
        <nav class="navbar navbar-expand-sm navbar-dark bg-main">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Sample</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div id="nav">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'app:list' %}">一覧</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'app:contact_form' %}">お問い合わせ</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <!-- フッター -->
    <footer class="border-top mt-4">
        <div class="py-4">
            <div class="d-flex justify-content-center text-muted">
                © {% now "Y" %} Sample. All Rights Reserved.
            </div>
        </div>
    </footer>
</body>

</html>

templates/contact_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>お問い合わせ</title>
{% endblock %}

{% block content %}
<!-- 問合せフォーム -->
<div class="content">
    <div class="container my-5">
        <h1>お問い合わせ</h1>
        <div class="my-3">
            <form method="post" action="" class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mt-3">
                    <button type="submit" class="submit btn btn-dark">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contact_result.html
{% extends "base.html" %}

{% block head %}
<title>お問い合わせ完了</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="container my-5">
        <div class="row">
            <div class="col-md-8">
                <h1>お問い合わせ完了</h1>
                <div class="my-3">
                    <p>お問い合わせは正常に送信されました。</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ detail.title }}</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="container my-5">
        <div class="row">
            <div class="col-md-8">
                <!-- カテゴリ、タグ -->
                <div class="d-flex justify-content-start align-items-center">
                    <div class="py-2">
                        <a href="{% url 'app:list' %}?category={{detail.category.id}}"
                            class="box bg-category">{{ detail.category }}</a>
                        {% for tag in detail.tag.all %}
                        <a href="{% url 'app:list' %}?tag={{tag.id}}"
                            class="box bg-tag">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <!-- 作成日時、更新日時 -->
                <div class="d-flex justify-content-end align-items-center">
                    {% if detail.newadddate|date:"Ymd" != detail.updatedate|date:"Ymd" %}
                    <div class="px-2">
                        <img src="{% static 'images/update_watch.svg' %}" alt="">
                        <label>{{ detail.updatedate | date:"Y/m/d"}}</label>
                    </div>
                    {% endif %}
                    <div class="px-2">
                        <img src="{% static 'images/upload_watch.svg' %}" alt="">
                        <label>{{ detail.newadddate | date:"Y/m/d"}}</label>
                    </div>
                </div>
                <!-- タイトル -->
                <h1>{{ detail.title }}</h1>
                <!-- 内容 -->
                <div class="img-link">
                    <img src="/media/{{ detail.image }}" class="img-thumbnail w-100" alt="">
                    <div id='toc-range'>
                        <p>{{ detail.content | safe }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ title }}</title>
{% endblock %}

{% block content %}
<div class="content">
    <div class="container my-5">
        <div class="row">
            <div class="col-lg-8">
                <h1>一覧</h1>
                <div class="card card-body mb-2">
                    <form method="GET" action="{% url 'app:list' %}" class="form-group">
                        {{ searchform }}
                        <div class="mt-3">
                            <button type="submit" class="submit btn btn-dark">検索</button>
                        </div>
                    </form>
                </div>
                <div class="row row-cols-1">
                    {% for element in list %}
                    <div class="col">
                        <div class="card-box">
                            <div class="card mb-1">
                                <div class="row g-0">
                                    <div class="col-4">
                                        <img src="/media/{{ element.image }}" class="img-fluid" alt="" />
                                    </div>
                                    <div class="col-8">
                                        <div class="card-body p-2">
                                            <div class="card-title" style="font-weight:bold;">{{ element.title | truncatechars:50 }}</div>
                                            <small class="text-muted">{{ element.newadddate | date:"Y/m/d H:i"}}</small>
                                            <span class="box bg-category">{{ element.category }}</span>
                                            <a href="{% url 'app:detail' element.id %}" class="stretched-link"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- ページネーション -->
                <div class="d-flex justify-content-center">
                    <ul class="pagination">
                        <!-- 前へ の部分 -->
                        {% if list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'app:list' %}?page={{list.previous_page_number}}">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}
                
                        <!-- 数字の部分 -->
                        {% for num in list.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link text-dark" href="{% url 'app:list' %}?page={{num}}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                
                        <!-- 次へ の部分 -->
                        {% if list.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'app:list' %}?page={{list.next_page_number}}">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}